### ISSUE TITLE
Kommentarer til Brownstone & Train book 24/5-2023

### ISSUE THREAD

**Issue by NikolajNielsenEcon** [FrederikRomberg/GREENCAR_notebooks#20]
Her er alle de kommentarer jeg har skrevet ned, med stjerner efter vigtighed (3 er højest)

1)*** Når der præsenteres estimater, så lav regressionstabel med variabelnavne, standardfejl og stjerner.
2)*    Nævn i forklaring af IPDL at q' ln q er (minus) entropien af q, og at det giver logit hvis lambda=0
3)** Tuborgklammer om max/argmax udtryk
4)**  Flere forklaringer af teorien
5)*   I Create_Gamma (eller hvad den nu hed), lav variablen "nests" om til C_g (eller num_nests_g) og fjern den fra return
6)*   Generelt er Gamma funktionen svær at læse. Kig på at simplificere koden, eller lav en simpel og en hurtig version.
7)** Benyt broadcasting når muligt, e.g. qqt=q[:,:,None]*q[:,None,:] 
8)*** Lav separat FKN notebook, det bliver for meget at forstå på en gang.

Desuden forslag fra Mogens: 
1) Kig på tolkning af komplementaritet: er det de "rigtige" par af biler der er komplementer?  
2) Lad nesting parametrene være forskellige for hver nest (se IPDL paper appendix)

**Comment by FrederikRomberg** [comment]
Følgende mangler:

1)*** Når der præsenteres estimater, så lav regressionstabel med variabelnavne, standardfejl og stjerner.
4)** Flere forklaringer af teorien
6)* Generelt er Gamma funktionen svær at læse. Kig på at simplificere koden, eller lav en simpel og en hurtig version.
7)** Benyt broadcasting når muligt, e.g. qqt=q[:,:,None]q[:,None,:]
8)** Lav separat FKN notebook, det bliver for meget at forstå på en gang.

+ Mogens' forslag

**Comment by FrederikRomberg** [comment]
Følgende mangler:
1) ***stjerner?
4)** Flere forklaringer af teorien
6)* Generelt er Gamma funktionen svær at læse. Kig på at simplificere koden, eller lav en simpel og en hurtig version.
8)** Lav separat FKN notebook, det bliver for meget at forstå på en gang.

Mogens' forslag

**Comment by FrederikRomberg** [comment]
Følgende mangler:
4)** Flere forklaringer af teorien
6)* Generelt er Gamma funktionen svær at læse. Kig på at simplificere koden, eller lav en simpel og en hurtig version.

Mogens' forslag

**Comment by FrederikRomberg** [comment]
Følgende mangler:
4)** Flere forklaringer af teorien

Mogens' forslag
